# Utilisation de numpy

In [ ]:
Sources
https://www.youtube.com/watch?v=NzDQTrqsxas
Python pour la Data Science - Jake VanderPlas

### Premier tableau à n dimensions (ndarray) et quelques attributs généralement utilisés


In [14]:
import numpy as np

# tableau à 1 dimension
tab1 = np.array([1,2,3])

# afficher la dimension du tableau
print("Dimension : ", tab1.ndim)
# afficher la forme du tableau
print("Forme : ", tab1.shape)
# afficher le nombre d'éléments dans le tableau
print("Nombre éléments : ", tab1.size)

Dimension :  1
Forme :  (3,)
Nombre éléments :  3


### Quelques méthodes

In [26]:
import numpy as np

# Créer un tableau de 3 lignes et 2 colonnes rempli de 0
tab2 = np.zeros((3,2))
print('Tableau rempli de 0')
print(tab2, '\n')
# Créer un tableau de 4 lignes et 3 colonnes rempli de 1
tab3 = np.ones((4,3))
print('Tableau rempli de 1')
print(tab3, '\n')
# Créer un tableau rempli de nombres aléatoires
print('Tableau rempli de nombres aléatoires - basiquement distributio normale centrée autour de 0')
tab3 = np.random.randn(3,4)  # Attention pas de tuple ici
print(tab3)

Tableau rempli de 0
[[0. 0.]
 [0. 0.]
 [0. 0.]] 

Tableau rempli de 1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

Tableau rempli de nombres aléatoires - basiquement distributio normale centrée autour de 0
[[-0.49243806 -0.62341014 -1.41668896  1.65038992]
 [-0.8605063   0.20440733 -1.33885014  0.58425573]
 [-0.48539778 -0.63856357  0.10982584 -0.48028599]]
